name: girl_friend
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: '>=2.17.6 <3.0.0'

dependencies:
    animations: ^2.0.3
    bloc_concurrency: ^0.2.0
    cached_network_image: ^3.2.1
    carousel_slider: ^4.1.1
    collection: ^1.16.0
    connectivity_plus: ^2.3.5
    cupertino_icons: ^1.0.2
    dio: ^4.0.6
    firebase_analytics: ^9.3.4
    firebase_core: ^1.22.0
    firebase_crashlytics: ^2.8.10
    firebase_dynamic_links: ^4.3.7
    firebase_messaging: ^13.0.1
    firebase_remote_config: ^2.0.17
    flutter:
        sdk: flutter
    flutter_bloc: ^8.0.1
    flutter_chat_types: ^3.4.4
    flutter_link_previewer: ^3.0.1
    flutter_localizations:
        sdk: flutter
    flutter_native_splash: ^2.2.8
    flutter_rating_bar: ^4.0.1
    flutter_secure_storage: ^6.0.0
    flutter_slidable: ^2.0.0
    flutter_svg: ^1.1.0
    freezed_annotation: ^2.1.0
    get_it: ^7.2.0
    go_router: ^5.0.1
    hive_flutter: ^1.1.0
    intl: ^0.17.0
    json_annotation: ^4.6.0
    lottie: ^1.3.0
    percent_indicator: ^4.2.2
    permission_handler: ^10.0.0
    pinput: ^2.2.11
    shimmer: ^2.0.0
    url_launcher: ^6.1.5
    uuid: ^3.0.6
    webview_flutter: ^3.0.4

dev_dependencies:
    build_runner: ^2.2.0
    flutter_launcher_icons: ^0.10.0
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    freezed: ^2.1.0+1
    hive_generator: ^1.1.3
    intl_utils: ^2.7.0
    json_serializable: ^6.3.1

flutter_native_splash:
    color: '#FFFFFF'
    color_dark: '#202124'
    image: 'assets/images/logo_splash.png'

flutter_intl:
    enabled: true
    class_name: AppLanguage
    main_locale: vi
    arb_dir: lib/localization/l10n
    output_dir: lib/localization

flutter:
    uses-material-design: true
    assets:
        - assets/illustration/
        - assets/images/
        - assets/icons/
        - assets/jsons/

    fonts:
        - family: Montserrat
          fonts:
              - asset: assets/fonts/Montserrat-ExtraLight.ttf
                weight: 200
              - asset: assets/fonts/Montserrat-Light.ttf
                weight: 300
              - asset: assets/fonts/Montserrat-Regular.ttf
                weight: 400
              - asset: assets/fonts/Montserrat-Medium.ttf
                weight: 500
              - asset: assets/fonts/Montserrat-SemiBold.ttf
                weight: 600
              - asset: assets/fonts/Montserrat-Bold.ttf
                weight: 700
              - asset: assets/fonts/Montserrat-ExtraBold.ttf
                weight: 800
